### ISSUE TITLE
eval does not accept quoted arguments correctly

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_03#13]
**Describe the bug**
```
| makeresults count=1 | eval estimate(tokens)=_time | eval foo=tonumber('estimate(tokens)')
```

throws
```
java.lang.IllegalStateException: failed to parse at line 3:90 due to mismatched input ')' expecting {EVAL_LANGUAGE_MODE_COMMA, EVAL_LANGUAGE_MODE_DEQ, EVAL_LANGUAGE_MODE_EQ, EVAL_LANGUAGE_MODE_NEQ, EVAL_LANGUAGE_MODE_LT, EVAL_LANGUAGE_MODE_LTE, EVAL_LANGUAGE_MODE_GT, EVAL_LANGUAGE_MODE_GTE, EVAL_LANGUAGE_MODE_DOT, EVAL_LANGUAGE_MODE_AND, EVAL_LANGUAGE_MODE_OR, EVAL_LANGUAGE_MODE_XOR, EVAL_LANGUAGE_MODE_WILDCARD, EVAL_LANGUAGE_MODE_PLUS, EVAL_LANGUAGE_MODE_MINUS, EVAL_LANGUAGE_MODE_SLASH, EVAL_LANGUAGE_MODE_Like, EVAL_LANGUAGE_MODE_PERCENT, EVAL_LANGUAGE_MODE_LIKE}
```
 
**Expected behavior**
should work correctly

**How to Reproduce**
run the query
 
**Screenshots**
none
 
**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any
 
**Additional context**
com.teragrep-pth_07-5.14.0.3.g2d92443a.x86_64-1329.x86_64

**Comment by 51-code** [comment]
eval tonumber required the base of the number as a second parameter. Changed it so that it is optional.

No changes needed in pth-10, it already operates under the assumption that the parameter is optional.
